Improve handling of default colours
joshestein/ideavim-quickscope pull request #9
Opened 2023-04-19 14:41 UTC by citizenmatt

This PR makes some minor changes to the highlights if you don't set your own custom colours:

* Use the default colours for the current editor theme, rather than just the default attributes. This works better with dark themes
* Calculate the default colours when adding highlights, which means colours are correct after a theme change
* Verify that the secondary colour is actually modified by the call to `brighter()`. If not, use `darker()` to get a different colour
* Use bold font and underline for the primary matches to help distinguish between primary and secondary matches by something other than colour, which is very helpful for my mild colourblindness

2023-04-21 16:39 UTC, joshestein requested changes
Thank you for the PR!

2023-04-21 16:39 UTC, joshestein commented on src/main/kotlin/com/joshestein/ideavimquickscope/Highlighter.kt
> +                ?: EditorColors.REFERENCE_HYPERLINK_COLOR.defaultAttributes.foregroundColor
Could we move these back to where the `primaryColor` and `secondaryColor` are initialised? Otherwise we run these fallback checks everytime we want to add highlights (frequently!).

2023-04-21 18:03 UTC, joshestein approved these changes

2023-04-21 18:12 UTC, merged

2023-04-21 18:17 UTC, citizenmatt commented on src/main/kotlin/com/joshestein/ideavimquickscope/Highlighter.kt
> +                ?: EditorColors.REFERENCE_HYPERLINK_COLOR.defaultAttributes.foregroundColor
This was a deliberate move to make sure that we're always using the correct colours for the theme, and not caching incorrect colours.

2023-04-21 18:21 UTC, citizenmatt commented on src/main/kotlin/com/joshestein/ideavimquickscope/Highlighter.kt
> +            ?: EditorColors.REFERENCE_HYPERLINK_COLOR.defaultAttributes.foregroundColor
I think initialising here will cache this value for the duration of the plugin, so it won't update when the theme changes, e.g. from light to dark when "sync with OS" is selected.

2023-04-22 08:29 UTC, joshestein commented on src/main/kotlin/com/joshestein/ideavimquickscope/Highlighter.kt
> +            ?: EditorColors.REFERENCE_HYPERLINK_COLOR.defaultAttributes.foregroundColor
Ah, I understand now 👍 

Even though this isn't an expensive call, I'd prefer to initialise it once (and incorrectly cache it). I think people are changing their themes fairly infrequently, whereas the call to `addHighlights` happens much more frequently.

I think it makes more sense to have an incorrectly cached color only some of the time compared to adding additional overhead most of the time? What do you think?

2023-04-22 09:59 UTC, citizenmatt commented on src/main/kotlin/com/joshestein/ideavimquickscope/Highlighter.kt
> +            ?: EditorColors.REFERENCE_HYPERLINK_COLOR.defaultAttributes.foregroundColor
I use the "sync with OS" option, so my theme changes twice a day 😁 

I think getting colours once per highlight set would be fine, since the editor displays highlights as you type already. But then, I only highlight based on hitting `f` or `t`, etc. It might be a bit much for automatic highlighting. We can probably register a theme listener to clear the cache when the theme changes. I can take a look and make a new PR

2023-04-22 10:35 UTC, joshestein commented on src/main/kotlin/com/joshestein/ideavimquickscope/Highlighter.kt
> +            ?: EditorColors.REFERENCE_HYPERLINK_COLOR.defaultAttributes.foregroundColor
Oh! Okay, it makes much more sense! Sorry, that is very annoying 😞 

If you are willing to make that PR that would be awesome! Otherwise I can also take a crack later this week 👍